include 'zipf' and 'extract' functions.

diff --git a/sh-common b/sh-common
--- a/sh-common
+++ b/sh-common
@@ -349,6 +349,33 @@ function is_link {
   [ -L "$1" ]
 }
 
+function zipf {
+  [ ! -z "$1" ] || die "No argument passed to $0 function."
+  zip -r "$1".zip "$1"
+}
+
+function extract {
+  [ ! -z "$1" ] || die "No argument passed to $0 function."
+  if [ -f "$1" ]; then
+    case "$1" in
+      *.tar.bz2)   tar xjf $1     ;;
+      *.tar.gz)    tar xzf $1     ;;
+      *.bz2)       bunzip2 $1     ;;
+      *.rar)       unrar e $1     ;;
+      *.gz)        gunzip $1      ;;
+      *.tar)       tar xf $1      ;;
+      *.tbz2)      tar xjf $1     ;;
+      *.tgz)       tar xzf $1     ;;
+      *.zip)       unzip $1       ;;
+      *.Z)         uncompress $1  ;;
+      *.7z)        7z x $1        ;;
+      *)     die "'$1' cannot be extracted via extract()" ;;
+    esac
+  else
+    die "'$1' is not a valid file."
+  fi
+}
+
 # Make sure that we delete the temp files when we exit
 trap 'clean_up' EXIT
 clear_vars
